Read results

In [ ]:
import pickle

with open("../results/results_blind.pkl", "rb") as f:
    blindresults = pickle.load(f)

with open("../results/best_voxels_ctrlAV.pkl", "rb") as f:
    AVresults = pickle.load(f)

with open("../results/results_ctrlA.pkl", "rb") as f:
    Aresults = pickle.load(f)

In [4]:
blindresults

{33: defaultdict(dict,
             {2: {'Llama_layers_layers7-11': array([-0.07472442,  0.05649629, -0.12808115, ...,  0.13415818,
                      -0.07190816, -0.02198396], shape=(1577,)),
               'CLIPmultilingualmulti_layers11-15': array([-0.16126203, -0.09798188, -0.13039031, ...,  0.1194671 ,
                      -0.09610913,  0.01857189], shape=(1577,)),
               'qwen-audiovideotext_layers16-20': array([ 0.02025683,  0.04180289,  0.08015325, ..., -0.15147962,
                       0.08664295,  0.06267042], shape=(1577,)),
               'CLIPmultilingualtext_layers11-15': array([-0.10713475, -0.04603841, -0.01014534, ...,  0.04339301,
                      -0.05423089,  0.03890936], shape=(1577,)),
               'XLM-roberta_layers11-15': array([-0.01123579,  0.11465553,  0.09396024, ..., -0.01827629,
                       0.13438538, -0.04318322], shape=(1577,)),
               'binder_abstractness': array([ 0.19488525,  0.01242506, -0.12912221, ...,  0.

In [5]:
import pandas as pd

groups = {
   'blind': blindresults,
   'AV': AVresults,
   'A': Aresults
}

def flatten_results_to_df(groups_dict):
    rows = []

    for group_name, participants in groups_dict.items():

        for participant_id, rois in participants.items():

            for roi_id, model_dict in rois.items():

                for model_name, arr in model_dict.items():

                    # arr is a numpy array → iterate through each value
                    for idx, value in enumerate(arr):
                        rows.append({
                            "group": group_name,
                            "participant": participant_id,
                            "roi": roi_id,
                            "model": model_name,
                            "index": idx,
                            "value": value
                        })

    return pd.DataFrame(rows)

df = flatten_results_to_df(groups)

print(df.head())

   group  participant roi                    model  index     value
0  blind           33   2  Llama_layers_layers7-11      0 -0.074724
1  blind           33   2  Llama_layers_layers7-11      1  0.056496
2  blind           33   2  Llama_layers_layers7-11      2 -0.128081
3  blind           33   2  Llama_layers_layers7-11      3  0.130229
4  blind           33   2  Llama_layers_layers7-11      4 -0.071431


Add qwentext results

In [9]:
with open("../results/qwentext/results_blind.pkl", "rb") as f:
    blindresultsq = pickle.load(f)

with open("../results/qwentext/results_ctrlAV.pkl", "rb") as f:
    AVresultsq = pickle.load(f)

with open("../results/qwentext/results_ctrlA.pkl", "rb") as f:
    Aresultsq = pickle.load(f)

In [23]:
newgroups = {
   'blind': blindresultsq,
   'AV': AVresultsq,
   'A': Aresultsq
}

df_new = flatten_results_to_df(newgroups)

models_to_remove = ['binder_concreteness', 'binder_abstractness']

df_new_filtered = df_new[~df_new['model'].isin(models_to_remove)]

df_all = pd.concat([df, df_new_filtered], ignore_index=True)


In [26]:
df_all

group  participant   roi                       model  index     value
0        blind           33     2     Llama_layers_layers7-11      0 -0.074724
1        blind           33     2     Llama_layers_layers7-11      1  0.056496
2        blind           33     2     Llama_layers_layers7-11      2 -0.128081
3        blind           33     2     Llama_layers_layers7-11      3  0.130229
4        blind           33     2     Llama_layers_layers7-11      4 -0.071431
...        ...          ...   ...                         ...    ...       ...
3201587      A           27  face  qwen-text_layers16-20_conv   1572  0.072127
3201588      A           27  face  qwen-text_layers16-20_conv   1573 -0.067048
3201589      A           27  face  qwen-text_layers16-20_conv   1574 -0.072001
3201590      A           27  face  qwen-text_layers16-20_conv   1575 -0.070897
3201591      A           27  face  qwen-text_layers16-20_conv   1576  0.044024

[3201592 rows x 6 columns]

Add semantic results

In [28]:
with open("../results/semantic/results_semantic.pkl", "rb") as f:
    semanticresults = pickle.load(f)

print(semanticresults)

{('binder_concreteness', 'Llama_layers_layers7-11'): array([-0.029333  , -0.03696641,  0.03942497, ...,  0.00633964,
        0.00707369,  0.00748555], shape=(1577,)), ('binder_concreteness', 'CLIPmultilingualmulti_layers11-15'): array([ 0.11705375,  0.1144265 ,  0.11454238, ..., -0.05413075,
       -0.04792858, -0.04692644], shape=(1577,)), ('binder_concreteness', 'qwen-text_layers16-20_conv'): array([ 0.06959846,  0.10228053,  0.06608655, ...,  0.10551191,
        0.09112249, -0.07064948], shape=(1577,)), ('binder_concreteness', 'qwen-audiovideotext_layers16-20'): array([ 0.03039857,  0.04032052,  0.05169334, ...,  0.11369727,
        0.1018167 , -0.04168547], shape=(1577,)), ('binder_concreteness', 'CLIPmultilingualtext_layers11-15'): array([ 0.13917391,  0.12873833,  0.12423615, ..., -0.02152618,
       -0.01561056, -0.01451901], shape=(1577,)), ('binder_concreteness', 'XLM-roberta_layers11-15'): array([0.08773513, 0.13049882, 0.03640405, ..., 0.06752426, 0.06714298,
       0.066927

In [29]:
import numpy as np

# The original correlation dict:
# corr_dict = { (binder_model, model_name): array([...]), ... }

corr_conc = {
    model: arr
    for (binder, model), arr in semanticresults.items()
    if binder == 'binder_concreteness'
}

corr_abs = {
    model: arr
    for (binder, model), arr in semanticresults.items()
    if binder == 'binder_abstractness'
}


In [30]:
df_all["corr_concreteness"] = np.nan
df_all["corr_abstractness"] = np.nan


In [31]:
for model_name, arr in corr_conc.items():
    mask = df_all["model"] == model_name
    df_all.loc[mask, "corr_concreteness"] = arr[df_all.loc[mask, "index"].values]
    
for model_name, arr in corr_abs.items():
    mask = df_all["model"] == model_name
    df_all.loc[mask, "corr_abstractness"] = arr[df_all.loc[mask, "index"].values]


In [32]:
df_all

group  participant   roi                       model  index  \
0        blind           33     2     Llama_layers_layers7-11      0   
1        blind           33     2     Llama_layers_layers7-11      1   
2        blind           33     2     Llama_layers_layers7-11      2   
3        blind           33     2     Llama_layers_layers7-11      3   
4        blind           33     2     Llama_layers_layers7-11      4   
...        ...          ...   ...                         ...    ...   
3201587      A           27  face  qwen-text_layers16-20_conv   1572   
3201588      A           27  face  qwen-text_layers16-20_conv   1573   
3201589      A           27  face  qwen-text_layers16-20_conv   1574   
3201590      A           27  face  qwen-text_layers16-20_conv   1575   
3201591      A           27  face  qwen-text_layers16-20_conv   1576   

            value  corr_concreteness  corr_abstractness  
0       -0.074724          -0.029333           0.030983  
1        0.056496          -0.036966          -0.029370  
2       -0.128081           0.039425           0.005320  
3        0.130229           0.046623           0.064804  
4       -0.071431           0.057476           0.072272  
...           ...                ...                ...  
3201587  0.072127           0.133422           0.124665  
3201588 -0.067048           0.124213           0.090562  
3201589 -0.072001           0.105512           0.048710  
3201590 -0.070897           0.091122           0.026334  
3201591  0.044024          -0.070649          -0.112060  

[3201592 rows x 8 columns]

In [33]:
df_all.to_csv("../results/results.csv", sep=";", index=False)


In [34]:
with open("../results/best_voxels_blind.pkl", "rb") as f:
    bv = pickle.load(f)

In [35]:
bv

{33: defaultdict(dict,
             {2: {'Llama_layers_layers7-11': [array([142,  74,  31, 221,  62, 139, 226,  50, 268, 333, 259,  81, 307,
                        21,  30,   6, 227,  66,  43,  51,  20, 149,  35,  87,   0, 280,
                       237, 135, 285, 335,  71,  78, 262, 260]),
                array([268,  85, 259,   8, 275, 262, 231,  46,  45, 285, 208, 307, 150,
                        74,  37, 149, 267, 226,  47, 227,  98, 193,  86,  31,  99, 284,
                       250, 221, 232,  38,   9, 142,  55, 163]),
                array([221,  73, 142,  74,   3, 333,  66, 149, 135, 148,  62, 307,  31,
                       280, 136, 335, 163, 262, 336, 316,  38, 225, 181, 259, 231, 268,
                       168, 189,  86,  11, 313,   9, 321,  65]),
                array([ 39,  38,  86,  87,  47, 163, 259,  31,  74, 120,  99,  30,  37,
                       268,  98,  46, 269,  11, 197,  29, 148,  15, 142, 151, 246, 237,
                       333, 267, 307, 238,  16, 